// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7CUzBiBoCmrWyHqxwe8bDZK0vMDA7LuM',
    appId: '1:584422072082:web:17ce9b8196575068aa5dcb',
    messagingSenderId: '584422072082',
    projectId: 'flutter-ai-playground-d68ac',
    authDomain: 'flutter-ai-playground-d68ac.firebaseapp.com',
    storageBucket: 'flutter-ai-playground-d68ac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZUUgZ5S1t40JHQhHUFlmhL1hB32B7UtA',
    appId: '1:584422072082:android:0c31b4c47a9fbc6baa5dcb',
    messagingSenderId: '584422072082',
    projectId: 'flutter-ai-playground-d68ac',
    storageBucket: 'flutter-ai-playground-d68ac.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8dvkydCcJBW8MGHGs1GLbg9k5n-MrmGM',
    appId: '1:584422072082:ios:ae9d8dcf56cda7f1aa5dcb',
    messagingSenderId: '584422072082',
    projectId: 'flutter-ai-playground-d68ac',
    storageBucket: 'flutter-ai-playground-d68ac.firebasestorage.app',
    iosBundleId: 'com.medglobalnetwork.medglobalnetwork',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8dvkydCcJBW8MGHGs1GLbg9k5n-MrmGM',
    appId: '1:584422072082:ios:ae9d8dcf56cda7f1aa5dcb',
    messagingSenderId: '584422072082',
    projectId: 'flutter-ai-playground-d68ac',
    storageBucket: 'flutter-ai-playground-d68ac.firebasestorage.app',
    iosBundleId: 'com.medglobalnetwork.medglobalnetwork',
  );
}
